/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VlogRouteImport } from './routes/vlog'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MediaRouteImport } from './routes/media'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PracticeImmigrationLawRouteImport } from './routes/practice.immigration-law'
import { Route as PracticeHowCourtThinksRouteImport } from './routes/practice.how-court-thinks'
import { Route as PracticeAdministrativeLawRouteImport } from './routes/practice.administrative-law'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VlogRoute = VlogRouteImport.update({
  id: '/vlog',
  path: '/vlog',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeImmigrationLawRoute = PracticeImmigrationLawRouteImport.update({
  id: '/immigration-law',
  path: '/immigration-law',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeHowCourtThinksRoute = PracticeHowCourtThinksRouteImport.update({
  id: '/how-court-thinks',
  path: '/how-court-thinks',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeAdministrativeLawRoute =
  PracticeAdministrativeLawRouteImport.update({
    id: '/administrative-law',
    path: '/administrative-law',
    getParentRoute: () => PracticeRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/media': typeof MediaRoute
  '/practice': typeof PracticeRouteWithChildren
  '/vlog': typeof VlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/practice/administrative-law': typeof PracticeAdministrativeLawRoute
  '/practice/how-court-thinks': typeof PracticeHowCourtThinksRoute
  '/practice/immigration-law': typeof PracticeImmigrationLawRoute
  '/blog/': typeof BlogIndexRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/media': typeof MediaRoute
  '/vlog': typeof VlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/practice/administrative-law': typeof PracticeAdministrativeLawRoute
  '/practice/how-court-thinks': typeof PracticeHowCourtThinksRoute
  '/practice/immigration-law': typeof PracticeImmigrationLawRoute
  '/blog': typeof BlogIndexRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/media': typeof MediaRoute
  '/practice': typeof PracticeRouteWithChildren
  '/vlog': typeof VlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/practice/administrative-law': typeof PracticeAdministrativeLawRoute
  '/practice/how-court-thinks': typeof PracticeHowCourtThinksRoute
  '/practice/immigration-law': typeof PracticeImmigrationLawRoute
  '/blog/': typeof BlogIndexRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/media'
    | '/practice'
    | '/vlog'
    | '/blog/$slug'
    | '/practice/administrative-law'
    | '/practice/how-court-thinks'
    | '/practice/immigration-law'
    | '/blog/'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/media'
    | '/vlog'
    | '/blog/$slug'
    | '/practice/administrative-law'
    | '/practice/how-court-thinks'
    | '/practice/immigration-law'
    | '/blog'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/media'
    | '/practice'
    | '/vlog'
    | '/blog/$slug'
    | '/practice/administrative-law'
    | '/practice/how-court-thinks'
    | '/practice/immigration-law'
    | '/blog/'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  MediaRoute: typeof MediaRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  VlogRoute: typeof VlogRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vlog': {
      id: '/vlog'
      path: '/vlog'
      fullPath: '/vlog'
      preLoaderRoute: typeof VlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/immigration-law': {
      id: '/practice/immigration-law'
      path: '/immigration-law'
      fullPath: '/practice/immigration-law'
      preLoaderRoute: typeof PracticeImmigrationLawRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/how-court-thinks': {
      id: '/practice/how-court-thinks'
      path: '/how-court-thinks'
      fullPath: '/practice/how-court-thinks'
      preLoaderRoute: typeof PracticeHowCourtThinksRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/administrative-law': {
      id: '/practice/administrative-law'
      path: '/administrative-law'
      fullPath: '/practice/administrative-law'
      preLoaderRoute: typeof PracticeAdministrativeLawRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PracticeRouteChildren {
  PracticeAdministrativeLawRoute: typeof PracticeAdministrativeLawRoute
  PracticeHowCourtThinksRoute: typeof PracticeHowCourtThinksRoute
  PracticeImmigrationLawRoute: typeof PracticeImmigrationLawRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeAdministrativeLawRoute: PracticeAdministrativeLawRoute,
  PracticeHowCourtThinksRoute: PracticeHowCourtThinksRoute,
  PracticeImmigrationLawRoute: PracticeImmigrationLawRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  MediaRoute: MediaRoute,
  PracticeRoute: PracticeRouteWithChildren,
  VlogRoute: VlogRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
